[package]
name = "rust-toy-tx-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
log = "0.4.27"
rust_decimal = "1.37.2"
serde = { version = "1.0.219", features = ["derive"] }
